/*  =========================================================================
    wallet - WALLET wrapper

    Copyright (c) the Contributors as noted in the AUTHORS file.
                                                                
    (insert license text here)                                  

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef __wap_library_H_INCLUDED__
#define __wap_library_H_INCLUDED__

//  External dependencies
#include <czmq.h>

//  WALLET version macros for compile-time API detection

#define WALLET_VERSION_MAJOR 0
#define WALLET_VERSION_MINOR 0
#define WALLET_VERSION_PATCH 1

#define WALLET_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define WALLET_VERSION \
    WALLET_MAKE_VERSION(WALLET_VERSION_MAJOR, WALLET_VERSION_MINOR, WALLET_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBWAP_STATIC
#       define WAP_EXPORT
#   elif defined LIBWAP_EXPORTS
#       define WAP_EXPORT __declspec(dllexport)
#   else
#       define WAP_EXPORT __declspec(dllimport)
#   endif
#else
#   define WAP_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _wap_proto_t wap_proto_t;
#define WAP_PROTO_T_DEFINED
typedef struct _wap_server_t wap_server_t;
#define WAP_SERVER_T_DEFINED
typedef struct _wap_client_t wap_client_t;
#define WAP_CLIENT_T_DEFINED


//  Public API classes
#include "wap_proto.h"
#include "wap_server.h"
#include "wap_client.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
