/*  =========================================================================
    wap_classes - private header file

    Copyright (c) the Contributors as noted in the AUTHORS file.
                                                                
    (insert license text here)                                  
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef __WAP_CLASSES_H_INCLUDED__
#define __WAP_CLASSES_H_INCLUDED__

//  External API
#include "../include/wallet.h"

//  Internal API

#endif
