package=zeromq
$(package)_version=4.3.5
$(package)_download_path=https://github.com/zeromq/libzmq/releases/download/v$($(package)_version)/
$(package)_file_name=$(package)-$($(package)_version).tar.gz
$(package)_sha256_hash=6653ef5910f17954861fe72332e68b03ca6e4d9c7160eb3a8de5a5a913bfab43
$(package)_build_subdir=build

define $(package)_set_vars
  $(package)_config_opts := -DBUILD_SHARED=OFF
  $(package)_config_opts += -DWITH_DOC=OFF
  $(package)_config_opts += -DZMQ_BUILD_TESTS=OFF
  $(package)_config_opts += -DZMQ_HAVE_IPC=OFF
endef

# Remove (autogenerated) files that are not present in the git source tree
define $(package)_preprocess_cmds
  rm ChangeLog configure Makefile.in aclocal.m4 builds/Makefile.in && \
  rm -rf doc config builds/deprecated-msvc
endef

define $(package)_config_cmds
  $($(package)_cmake) -S .. -B .
endef

define $(package)_build_cmds
  $(MAKE)
endef

define $(package)_stage_cmds
  $(MAKE) DESTDIR=$($(package)_staging_dir) install
endef

define $(package)_postprocess_cmds
  rm -rf share
endef
