#!/bin/bash
set -x
rm -rf build/
mkdir -p build
cd build && cmake -D CMAKE_BUILD_TYPE=Debug -D BOOST_IGNORE_SYSTEM_PATHS=ON -D BUILD_CONN_TOOL=OFF -D BUILD_SHARED_LIBS=ON -D BUILD_SIMPLE_MINER=OFF -D BUILD_SIMPLE_WALLET=OFF -D BUILD_TESTS=OFF -D ENABLE_COTIRE=ON -D COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES=1 -D COTIRE_VERBOSE=ON ..


make $@
