[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/kayabaNerve/crypto-bigint?branch=c-repr"]
git = "https://github.com/kayabaNerve/crypto-bigint"
branch = "c-repr"
replace-with = "vendored-sources"

[source."git+https://github.com/monero-oxide/monero-oxide?rev=50dd3dbc0cc9048247eb734d27eb1d516aecacd2"]
git = "https://github.com/monero-oxide/monero-oxide"
rev = "50dd3dbc0cc9048247eb734d27eb1d516aecacd2"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/rust/vendor"
