[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/kayabaNerve/crypto-bigint?branch=c-repr"]
git = "https://github.com/kayabaNerve/crypto-bigint"
branch = "c-repr"
replace-with = "vendored-sources"

[source."git+https://github.com/monero-oxide/monero-oxide?rev=31c26d96eaadbba910ffe3613ad8b4cf9c598a93"]
git = "https://github.com/monero-oxide/monero-oxide"
rev = "31c26d96eaadbba910ffe3613ad8b4cf9c598a93"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/rust/vendor"
