# Brewfile for Monero
# A homebrew Brewfile installs all required dependencies in one shot
# see https://coderwall.com/p/afmnbq/homebrew-s-new-feature-brewfiles
#     https://github.com/Homebrew/homebrew-bundle
# execute brew bundle in the directory containing the Brewfile

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "autoconf"
brew "autogen"
brew "automake"
brew "binutils"
brew "coreutils"
brew "cmake"
brew "pkgconfig"
brew "boost"
brew "openssl"
brew "openssl@1.1"
brew "hidapi"
brew "unbound"
brew "zeromq"
brew "libpgm"
brew "libsodium"
brew "readline"
brew "ldns"
brew "expat"
brew "ccache"
brew "doxygen"
brew "graphviz"
brew "libunwind-headers"
brew "xz"
brew "protobuf"