#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title tx_pool_size
graph_vlabel tx_pool_size
graph_category bytecoin
tx_pool_size.label tx_pool_size
EOM
        exit 0;;
esac

printf "tx_pool_size.value "
/home/user/bytecoin_bin/connectivity_tool --ip=127.0.0.1 --rpc_port=8081 --timeout=1000 --rpc_get_daemon_info | grep tx_pool_size| cut -d ' ' -f2
