name: "ci/gh-actions/docker-image"

on:
  push:
    tags: [ 'release-v*.*' ]

jobs:
  docker_buildx_debian:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: configure git
        run: git config --global --add safe.directory '*'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for tags
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version
        run: |
          export MONERO_VERSION="$(git describe --tags)"
          echo "MONERO_VERSION=$MONERO_VERSION" >> $GITHUB_ENV

      - name: Build and push latest Debian image
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: |
            linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/monero:latest
            ${{ vars.DOCKERHUB_USERNAME }}/monero:${{ env.MONERO_VERSION }}

